const numberTd = document.querySelectorAll('[appen-number]')
const operatorTd = document.querySelectorAll('[append-operator]')
const equalsTd = document.querySelectorAll('[append-equals]')
const deleteTd = document.querySelectorAll('[append-delete]')
const allClearTd = document.querySelectorAll('[append-all-clear]')
